---
- name: Redis | Install redis
  apt: pkg=redis-server state=installed
  tags: redis
  sudo: yes

- name: Redis | set redis port
  lineinfile: dest=/etc/redis/redis.conf regexp="^port = " insertafter="^port = " line="port {{ redis_port }}"
  tags: redis
  sudo: true