---
- hosts: all

  vars_files:
    - ../settings.yml

  tasks:
    - name: local actions destroy | delete local hosts.ini file
      file: dest=../host.ini state=absent
      delegate_to: 127.0.0.1
      sudo: true

    - name: local actions destroy | remove reference of host from local hosts file
      lineinfile:
          dest='{{ hosts_file_location }}'
          state=absent
          regexp='.*?\s{{ webserver_hostname }} {{ webserver_hostname_alias }} adminer.{{ webserver_hostname }} xhprof.{{ webserver_hostname }} logs.{{ webserver_hostname }}'
      delegate_to: 127.0.0.1
      sudo: true