---
- hosts: all

  vars_files:
    - ../settings.yml

  roles:
    - base
    - apache
#    - mysql
#    - php
#    - adminer
#    - sendmail
#    - imagemagick

  post_tasks:

    - name: Move default index.php file into webroot directory.
      template: src=templates/index.j2 dest=/var/www/site/webroot/index.php force=no

#    - include: tests/main.yml

  handlers:
    - include: common/handlers/main.yml