---
# RVM script will issue and error code despite a successful install, hence the suppression of errors.
- name: Ruby | Install RVM (and suppress fail)
  shell: curl -L https://get.rvm.io | bash -s stable --quiet-curl --auto-dotfiles --ruby={{ ruby_version }} creates=/home/{{ user }}/.rvm
  tags: ruby
  ignore_errors: true

- name: Ruby | Add RVM to bash profile
  lineinfile:
    dest=/home/{{ user }}/.bashrc
    state=present
    line='[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'
  tags: ruby