---
- name: Drush | install drush via composer
  command: composer global require drush/drush:6.*
  tags: drush

- name: Drush | set drush to executable
  command: chmod u+x drush chdir=/home/{{ user }}/.composer/vendor/drush/drush
  tags: drush

- name: Drush | link up the drush command so everyone can run it
  file: src=/home/{{ user }}/.composer/vendor/drush/drush/drush dest=/usr/bin/drush state=link
  tags: drush
  sudo: true

- name: Drush | run drush once as current user to finalise install
  command: drush
  tags: drush

- name: Drush | download the site audit module
  command: drush dl site_audit --yes chdir=/home/{{ user }}/.drush creates=/home/{{ user }}/.drush/site_audit
  tags: drush
  sudo: true

- name: Drush | download the hacked! module
  command: drush dl hacked --yes chdir=/home/{{ user }}/.drush creates=/home/{{ user }}/.drush/hacked
  tags: drush
  sudo: true

- name: Drush | download the Coder module
  command: drush dl coder --yes chdir=/home/{{ user }}/.drush creates=/home/{{ user }}/.drush/coder
  tags: drush
  sudo: true

- name: Drush | download the Registry Rebuild module
  command: drush dl registry_rebuild --yes
  tags: drush

- name: Drush | download Terminus for Pantheon
  git: repo=https://github.com/pantheon-systems/terminus.git dest=/home/{{ user }}/.drush/terminus
  tags: drush
  sudo: true

- name: Drush | download Terminus dependencies
  command: composer update --no-dev chdir=/home/{{ user }}/.drush/terminus
  tags: drush
  sudo: true

- name: Drush | clear drush cache
  command: drush cc all 
  tags: drush
