---
- name: PHP | install php packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
   - php5-fpm
   - php5-cli
   - php5-common
   - php5-curl
   - php5-json
   - php-pear
   - php5-gd
   - php5-mysql
   - php5-xmlrpc
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php memory_limit
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?memory_limit =" insertafter="^[#|;]?memory_limit =" line="memory_limit = {{ php_memory_limit }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli memory_limit
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?memory_limit =" insertafter="^[#|;]?memory_limit =" line="memory_limit = {{ php_memory_limit }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx max_execution_time
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli max_execution_time
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx post_max_size
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?post_max_size =" insertafter="^[#|;]?post_max_size =" line="post_max_size = {{ php_post_max_size }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli post_max_size
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?post_max_size =" insertafter="^[#|;]?post_max_size =" line="post_max_size = {{ php_post_max_size }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx upload_max_filesize
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?upload_max_filesize =" insertafter="^[#|;]?upload_max_filesize = " line="upload_max_filesize = {{ php_upload_max_filesize }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli upload_max_filesize
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?upload_max_filesize =" insertafter="^[#|;]?upload_max_filesize = " line="upload_max_filesize = {{ php_upload_max_filesize }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx max_execution_time
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli max_execution_time
  lineinfile: dest=/etc/php5/cli/php.ini regexp="[#|;]?max_execution_time =" insertafter="^[#|;]?max_execution_time =" line="max_execution_time = {{ php_max_execution_time }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx display_errors
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?display_errors =" insertafter="^[#|;]?display_errors =" line="display_errors = {{ php_display_errors }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli display_errors
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?display_errors =" insertafter="^[#|;]?display_errors =" line="display_errors = {{ php_display_errors }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx display_startup_errors
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?display_startup_errors =" insertafter="^[#|;]?display_startup_errors =" line="display_startup_errors = {{ php_display_startup_errors }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli display_startup_errors
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?display_startup_errors =" insertafter="^[#|;]?display_startup_errors =" line="display_startup_errors = {{ php_display_startup_errors }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx html_errors
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?html_errors =" insertafter="^[#|;]?html_errors =" line="html_errors = {{ php_html_errors }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli html_errors
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?html_errors =" insertafter="^[#|;]?html_errors =" line="html_errors = {{ php_html_errors }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php nginx date_timezone
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?date.timezone =" insertafter="^[#|;]?date.timezone =" line="date.timezone = {{ php_date_timezone }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | change php cli date_timezone
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^[#|;]?date.timezone =" insertafter="^[#|;]?date.timezone =" line="date.timezone = {{ php_date_timezone }}"
  tags: php
  sudo: true
  notify:
    - restart nginx

- name: PHP | configure cgi.fix_pathinfo
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="^[#|;]?cgi.fix_pathinfo=" insertafter="^[#|;]?cgi.fix_pathinfo=" line="cgi.fix_pathinfo=0"
  tags: php
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | configure FPM
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^[#|;]?listen = 127" insertafter="^[#|;]?listen = 127" line="listen = /var/run/php5-fpm.sock"
  tags: php
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | configure for nginx 1
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^[#|;]?group = www" insertafter="^[#|;]?group = www" line="group = vagrant"
  tags: php
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | configure for nginx 2
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^[#|;]?listen\.group = www" insertafter="^[#|;]?listen\.group = www" line="listen.group = vagrant"
  tags: php
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | configure for nginx 3
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="^[#|;]?listen\.mode = 0660" insertafter="^[#|;]?listen\.mode = 0660" line="listen.mode = 0660"
  tags: php
  sudo: true
  notify:
    - restart nginx
    - restart fpm

- name: PHP | restart fpm
  service: name=php5-fpm state=restarted
  sudo: true

- name: PHP | Check if Composer is installed (ignore if fails)
  raw: composer
  register: composer_installed
  ignore_errors: true
  tags: drush

- name: PHP | Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  when: composer_installed.stdout.find('command not found') != -1
  tags: php
  sudo: true

- name: PHP | Check if uploadprogress is installed (ignore if fails)
  command: pecl list | grep uploadprogress
  register: uploadprogress_installed
  tags: php

- name: PHP | Install PECL uploadprogress
  command: pecl install uploadprogress creates=/usr/lib/php5/20100525/uploadprogress.so
  when: uploadprogress_installed.stdout.find('uploadprogress') == -1
  tags: php
  sudo: true

- name: PHP | add PECL uploadprogress apache php.ini setting
  lineinfile: dest=/etc/php5/fpm/php.ini state=present line="extension=uploadprogress.so"
  tags: php
  sudo: true
  notify:
    - restart nginx