---
- name: Varnish | install varnish
  apt: pkg=varnish state=installed
  tags: varnish
  sudo: true

- name: Varnish | add varnish vcl
  template: src=varnish_defaultvcl.j2 dest=/etc/varnish/default.vcl
  tags: varnish
  sudo: true

- name: Varnish | add varnish config
  template: src=varnish_config.j2 dest=/etc/default/varnish
  tags: varnish
  sudo: true
  notify:
   - restart varnish

- name: Varnish | force secret file
  copy: src=secret.txt dest=/etc/varnish/secret
  tags: varnish
  sudo: true
  notify:
  - restart varnish